### ISSUE TITLE
problem with  functionGet ordering points by nearest neighbor algorithm

### ISSUE THREAD

**Issue by ricardsos** [karam-mustafa/laravel-geographical-calculator#20]
The algorithm returns the ranking of 85 sorted points the first time (this will decrease to 82), the second time it returns the ranking of 2 points but the total points is 82, this function is used inside a while loop, and I'm using clearResult() as the documentation says

**Comment by karam-mustafa** [comment]
@ricardsos Hi, could you provide an example, please, or if you could share us the points, so we can test them.
