### ISSUE TITLE
default unit KM and not Mile

### ISSUE THREAD

**Issue by Oxicode** [karam-mustafa/laravel-geographical-calculator#5]
why mile?

**Comment by karam-mustafa** [comment]
Actually, there are no reasons to keep units dealing with kilometers or miles on any units
you can implement your default options by using setOption function, and I'm not going to close this issue, to listen to the community's opinion

```php
// All of these units should be calculated or you can choose one of them only
->setOptions(['units' => [
      'km',
      'mile', 
      'm',
      'cm'
]]);
```
Thank you
